operations:

  root:

    get:
      operationId: getAllTasks
      summary: Get all tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                $ref: 'data.yaml#/schemas/TaskList'
        '400':
          $ref: '../errors.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../errors.yaml#/components/responses/InternalServerError'

    post:
      operationId: createTask
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'data.yaml#/schemas/Task'
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                $ref: 'data.yaml#/schemas/Task'
        '400':
          $ref: '../errors.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../errors.yaml#/components/responses/InternalServerError'

  with_task_id:

    get:
      operationId: getTaskById
      summary: Get a task by ID
      parameters:
        - $ref: '#/components/parameters/taskId'
      responses:
        '200':
          description: A task
          content:
            application/json:
              schema:
                $ref: 'data.yaml#/schemas/Task'
        '400':
          $ref: '../errors.yaml#/components/responses/BadRequest'
        '404':
          $ref: '../errors.yaml#/components/responses/NotFound'
        '500':
          $ref: '../errors.yaml#/components/responses/InternalServerError'

    put:
      operationId: updateTask
      summary: Update a task by ID
      parameters:
        - $ref: '#/components/parameters/taskId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'data.yaml#/schemas/Task'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: 'data.yaml#/schemas/Task'
        '400':
          $ref: '../errors.yaml#/components/responses/BadRequest'
        '404':
          $ref: '../errors.yaml#/components/responses/NotFound'
        '500':
          $ref: '../errors.yaml#/components/responses/InternalServerError'

    delete:
      operationId: deleteTask
      summary: Delete a task by ID
      parameters:
        - $ref: '#/components/parameters/taskId'
      responses:
        '204':
          description: Task deleted
        '400':
          $ref: '../errors.yaml#/components/responses/BadRequest'
        '404':
          $ref: '../errors.yaml#/components/responses/NotFound'
        '500':
          $ref: '../errors.yaml#/components/responses/InternalServerError'

components:
  parameters:
    taskId:
       name: taskId
       in: path
       required: true
       schema:
          type: integer
          format: int64
          description: Unique identifier for the task
