openapi: 3.0.0
info:
    title: Task Objects
    description: Task objects for the Task Management System
    version: '1.0'
paths: {}

components:

    schemas:

        TaskList:
            type: array
            items:
                $ref: "#/components/schemas/Task"

        Task:
            type: object
            required:
                - title
                - id
                - status
                - priority
            properties:
                id:
                    description: Unique identifier for the task
                    type: integer
                    minimum: 1
                    readOnly: true
                    nullable: true
                title:
                    description: Title of the task
                    type: string
                    maxLength: 512
                    minLength: 1
                description:
                    description: Description of the task
                    type: string
                    nullable: true
                status:
                    $ref: "#/components/schemas/TaskStatus"
                priority:
                    $ref: "#/components/schemas/TaskPriority"
                author:
                    description: User name of the author
                    type: string
                    readOnly: true
                    nullable: true
                assignee:
                    description: User name of the assignee
                    type: string
                    nullable: true

        TaskStatus:
            description: Status of the task
            type: string
            enum:
                - pending
                - in_progress
                - completed
            default: pending

        TaskPriority:
            description: Priority level of the task
            type: string
            enum:
                - low
                - medium
                - high
            default: medium


        CommentList:
            type: array
            items:
                $ref: "#/components/schemas/Comment"

        Comment:
            type: object
            required:
                - text
            properties:
                id:
                    description: Unique identifier for the comment
                    type: integer
                    minimum: 1
                    readOnly: true
                    nullable: true
                text:
                    description: Text of the comment
                    type: string
                    minLength: 1
                author:
                    description: User name of the author
                    type: string
                    readOnly: true
                    nullable: true
