openapi: 3.0.3
info:
    title: Simple Task Management System
    description: API for a simple task management system
    version: 1.0.0

components:
    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT

security:
    - BearerAuth: []

paths:

    /login:
        $ref: 'login.yaml#/operations/root'

    /tasks:
        $ref: 'tasks/operations.yaml#/operations/root'
    /tasks/{taskId}:
        $ref: 'tasks/operations.yaml#/operations/with_task_id'
