openapi: 3.0.3
info:
  title: Simple Task Management System
  description: API for a simple task management system
  version: 1.0.0


#########################
###                   ###
###      security     ###
###                   ###
#########################

components:

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: [ ]


#########################
###                   ###
###       paths       ###
###                   ###
#########################

paths:

  #########################
  ###       login       ###
  #########################

  /login:
    $ref: 'login.yaml#/paths/login'


  #########################
  ###       tasks       ###
  #########################

  /tasks:
    $ref: 'tasks.yaml#/paths/tasksOperations'

  /tasks/{taskId}:
    $ref: 'tasks.yaml#/paths/oneTaskOperations'

  /tasks/{taskId}/status:
    $ref: 'tasks.yaml#/paths/tasksStatus'

  /tasks/{taskId}/assignee:
    $ref: 'tasks.yaml#/paths/tasksAssignee'

  /tasks/my:
    $ref: 'tasks.yaml#/paths/tasksAssignedToMe'


  #########################
  ###      comments     ###
  #########################

  /tasks/{taskId}/comments:
    $ref: 'comments.yaml#/paths/commentsOperations'

  /tasks/{taskId}/comments/{commentId}:
    $ref: 'comments.yaml#/paths/oneCommentOperations'
